Rest_UserBundle : 
  type : rest
  resource: "@CatalogProjectUserBundle/Resources/config/routing_rest.yml"

Rest_AppManagementBundle: 
  type : rest
  resource: "@CatalogProjectAppManagementBundle/Resources/config/routing_rest.yml"

Articles_Rest : 
  type : rest
  resource: "@CatalogProjectAppManagementBundle/Resources/config/routing_rest.yml"

