User : 
  type: rest
  resource:     "CatalogProjectAppManagementBundle:User"
  name_prefix:  api_
  requirements:
        _method:  POST|GET

Company : 
  type: rest
  resource:     "CatalogProjectAppManagementBundle:Company"
  name_prefix:  api_
  requirements:
        _method:  POST|GET

Articles : 
  type: rest
  resource:     "CatalogProjectAppManagementBundle:Article"
  name_prefix:  api_
  requirements:
        _method:  POST|GET